language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.2.2
  - 2.3.0
  - 2.4.0

gemfile:
  - gemfiles/default-with-activesupport.gemfile
  - gemfiles/json.gemfile
  - gemfiles/yajl.gemfile

sudo: false
